### ISSUE TITLE
openca-ocspd-3.1.2-1.el7.x86_64  Requires: libpki.so.89()(64bit) error

### ISSUE THREAD

**Issue by audiem13** [openca/openca-ocspd#45]
If i install libpki.so.89, openca tells me i need 0.9.0.  If i install 0.9.0 it tells me I need libpki.so.89().

[root@ip-172-31-27-241 /]# yum localinstall /home/ec2-user/openca-ocspd-3.1.2-1.el7.x86_64.rpm
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Examining /home/ec2-user/openca-ocspd-3.1.2-1.el7.x86_64.rpm: openca-ocspd-3.1.2-1.el7.x86_64
Marking /home/ec2-user/openca-ocspd-3.1.2-1.el7.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package openca-ocspd.x86_64 0:3.1.2-1.el7 will be installed
--> Processing Dependency: libpki.so.89()(64bit) for package: openca-ocspd-3.1.2-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: openca-ocspd-3.1.2-1.el7.x86_64 (/openca-ocspd-3.1.2-1.el7.x86_64)
           Requires: libpki.so.89()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

[root@ip-172-31-27-241 /]# yum list libpki
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Installed Packages
libpki.x86_64                       0.9.0-1.el7                        installed

**Comment by kuzma00** [comment]
the same problem

**Comment by n8v8R** [comment]
Since this been reported earlier in GitHub https://github.com/openca/openca-ocspd/issues/43#issuecomment-423741502, via their mailing list and directly to the developer @opencrypto by email and neither did yield a response seems uncertain whether the code is anymore actively maintained.

**Comment by scottsavarese** [comment]
Not sure if this is actively maintained or not. However, I solved this by repackaging the RPM myself. It appears that he built the new RPM on a server with the old version of libpki installed. By updating the spec file to require the current version but having the old version on the box it caused the conflict. They didn't do much testing here.

To build your own I created a brand new Centos 7 host with the development tools installed. Then:

1. Install libpki and libpki-devel packages from the openca website. Use the most current ones. Currently 0.9.0
2. git clone the ocspd repo from github.
3. cd to that directory
4. Run ./configure to create a Makefile
5. Run 'make rpm' to build the rpm.

Note: I removed the reference to the "finger" command from the spec file and put my name as the packer. I might submit a pull request to use getent or something later on.

**Comment by fbnewtz-vcore** [comment]
The following packages also need to be installed to complete the compilation of openca-ocspd.

libxml2-devel
openssl-devel
openldap-devel
finger -- See Note in previous post if you do not want to install finger.

**Comment by ohaya** [comment]
Hi - Has anyone tried what [scottsavarese] tried?  I am having problems when I try to run the "make rpm":

|| find "openca-ocspd-3.1.2" -type d ! -perm -755 \
        -exec chmod u+rwx,go+rx {} \; -o \
  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -444 -exec /bin/sh /tmp/jl/openca-ocspd-master/build/install-sh -c -m a+r {} {} \; \
|| chmod -R a+r "openca-ocspd-3.1.2"
tardir=openca-ocspd-3.1.2 && ${TAR-tar} chof - "$tardir" | eval GZIP= gzip --best -c >openca-ocspd-3.1.2.tar.gz
make[2]: Leaving directory `/tmp/jl/openca-ocspd-master'
if test -d "openca-ocspd-3.1.2"; then find "openca-ocspd-3.1.2" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "openca-ocspd-3.1.2" || { sleep 5 && rm -rf "openca-ocspd-3.1.2"; }; else :; fi
make[1]: Leaving directory `/tmp/jl/openca-ocspd-master'
Building RPM package(s)...
/bin/sh: line 24: rpmbuild: command not found

Please advise!

Thanks,
Jim

**Comment by ohaya** [comment]
Hi - I got past  the rpmbuild problem (had to do "yum install rpm-build" (with a dash!!) but now I getting a different error when trying "make rpm"

[root@ip-192-168-114-98 openca-ocspd-master]# make rpm

Cleaning up old RPMs ... Done.
Creating spec file ... (openca-ocspd.spec.orig) --> (openca-ocspd.spec)
Building source package...
make[1]: Entering directory `/tmp/jl/openca-ocspd-master'
make  dist-gzip am__post_remove_distdir='@:'
make[2]: Entering directory `/tmp/jl/openca-ocspd-master'
if test -d "openca-ocspd-3.1.2"; then find "openca-ocspd-3.1.2" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "openca-ocspd-3.1.2" || { sleep 5 && rm -rf "openca-ocspd-3.1.2"; }; else :; fi
test -d "openca-ocspd-3.1.2" || mkdir "openca-ocspd-3.1.2"
 (cd src && make  top_distdir=../openca-ocspd-3.1.2 distdir=../openca-ocspd-3.1.2/src \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/tmp/jl/openca-ocspd-master/src'
 (cd ocspd && make  top_distdir=../../openca-ocspd-3.1.2 distdir=../../openca-ocspd-3.1.2/src/ocspd \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[4]: Entering directory `/tmp/jl/openca-ocspd-master/src/ocspd'
make[4]: Leaving directory `/tmp/jl/openca-ocspd-master/src/ocspd'
make[3]: Leaving directory `/tmp/jl/openca-ocspd-master/src'
 (cd docs && make  top_distdir=../openca-ocspd-3.1.2 distdir=../openca-ocspd-3.1.2/docs \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/tmp/jl/openca-ocspd-master/docs'
make[3]: Leaving directory `/tmp/jl/openca-ocspd-master/docs'
 (cd etc && make  top_distdir=../openca-ocspd-3.1.2 distdir=../openca-ocspd-3.1.2/etc \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/tmp/jl/openca-ocspd-master/etc'
make[3]: Leaving directory `/tmp/jl/openca-ocspd-master/etc'
test -n "" \
|| find "openca-ocspd-3.1.2" -type d ! -perm -755 \
        -exec chmod u+rwx,go+rx {} \; -o \
  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -444 -exec /bin/sh /tmp/jl/openca-ocspd-master/build/install-sh -c -m a+r {} {} \; \
|| chmod -R a+r "openca-ocspd-3.1.2"
tardir=openca-ocspd-3.1.2 && ${TAR-tar} chof - "$tardir" | eval GZIP= gzip --best -c >openca-ocspd-3.1.2.tar.gz
make[2]: Leaving directory `/tmp/jl/openca-ocspd-master'
if test -d "openca-ocspd-3.1.2"; then find "openca-ocspd-3.1.2" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "openca-ocspd-3.1.2" || { sleep 5 && rm -rf "openca-ocspd-3.1.2"; }; else :; fi
make[1]: Leaving directory `/tmp/jl/openca-ocspd-master'
Building RPM package(s)...
error: line 73: Tag takes single token only: Release:  1.rhpackage redhat-release is not installed

Anyone get this working?

Thanks,
Jim

**Comment by rjkothari** [comment]
I'm trying to install the OCSP responder on CentOS 7 and getting the same error.

Is it possible for anyone to share the correct RPM file for the OCSP responder installation so that we don't get the error "libpki.so.89()(64bit) is needed by openca-ocspd-3.1.2-1.el7.x86_64"

I'm not good at compilation etc. So, I will need help from someone who has the correct RPM.

@scottsavarese @ohaya  Please help.

**Comment by audiem13** [comment]
> I'm trying to install the OCSP responder on CentOS 7 and getting the same error.
> 
> Is it possible for anyone to share the correct RPM file for the OCSP responder installation so that we don't get the error "libpki.so.89()(64bit) is needed by openca-ocspd-3.1.2-1.el7.x86_64"
> 
> I'm not good at compilation etc. So, I will need help from someone who has the correct RPM.
> 
> @scottsavarese @ohaya Please help.

Use 3.1.3

**Comment by rjkothari** [comment]
OCSD 3.1.3 I found at https://www.freshports.org/security/openca-ocspd/ is for FreeBSD 11. 

Is it available for CentOS 7?

**Comment by StocktonC** [comment]
return same result even i used ver 3.1.3

**Comment by StocktonC** [comment]
when I try to run the "make rpm". it returns:

make[1]: Entering directory `/root/rpmbuild/BUILD/openca-ocspd-3.1.3'
Making all in src
make[2]: Entering directory `/root/rpmbuild/BUILD/openca-ocspd-3.1.3/src'
Making all in ocspd
make[3]: Entering directory `/root/rpmbuild/BUILD/openca-ocspd-3.1.3/src/ocspd'
gcc -DHAVE_CONFIG_H -I. -I../../src/ocspd/includes  -I.  -I/usr/include -DENABLE_ECDSA=1 -I/usr/include/libxml2 -I/us      r/include   -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=      4 -grecord-gcc-switches   -m64 -mtune=generic -fstack-check -maccumulate-outgoing-args -Werror -Wfatal-errors -MT ocs      pd-ocspd.o -MD -MP -MF .deps/ocspd-ocspd.Tpo -c -o ocspd-ocspd.o `test -f 'ocspd.c' || echo './'`ocspd.c
mv -f .deps/ocspd-ocspd.Tpo .deps/ocspd-ocspd.Pogcc -DHAVE_CONFIG_H -I. -I../../src/ocspd/includes  -I.  -I/usr/include -DENABLE_ECDSA=1 -I/usr/include/libxml2 -I/us      r/include   -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=      4 -grecord-gcc-switches   -m64 -mtune=generic -fstack-check -maccumulate-outgoing-args -Werror -Wfatal-errors -MT ocs      pd-core.o -MD -MP -MF .deps/ocspd-core.Tpo -c -o ocspd-core.o `test -f 'core.c' || echo './'`core.c
core.c: In function 'start_threaded_server':
core.c:58:13: error: 'PKI_TOKEN_STATUS_KEYPAIR_CHECK_ERR' undeclared (first use in this function)
   if (rv & (PKI_TOKEN_STATUS_KEYPAIR_CHECK_ERR   |
             ^
compilation terminated due to -Wfatal-errors.
make[3]: *** [ocspd-core.o] Error 1
make[3]: Leaving directory `/root/rpmbuild/BUILD/openca-ocspd-3.1.3/src/ocspd'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/rpmbuild/BUILD/openca-ocspd-3.1.3/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/rpmbuild/BUILD/openca-ocspd-3.1.3'
error: Bad exit status from /var/tmp/rpm-tmp.ERnbrB (%build)

RPM build errors:
    bogus date in %changelog: Thu Feb 20 2001 Massimiliano Pala <madwolf@openca.org>
    Bad exit status from /var/tmp/rpm-tmp.ERnbrB (%build)

anyone know how to solve this? 

Thanks.
